Drop unused /dev/ prefix to unbreak FreeBSD 11.0
uhidd.c:291:16: error: passing 'const char *' to parameter of type 'char *' discards qualifiers
      [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
                    basename(hi->dev));
                             ^~~~~~~
/usr/include/libgen.h:38:22: note: passing argument to parameter here
char    *basename(char *);
                        ^